recent_docs: 50

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
    
defaults:
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: default
