recent_docs: 50

layouts_dir: /
data_source: data
defaults:
  -
    scope:
      path: "data/tags/*.md"
    values:
      permalink: /:basename/
      layout: docs
      
plugins:
  - jekyll-optional-front-matter
  
#collections_dir: data
#collections:
#  tags:
#    output: true
#    permalink: /:collection/:path/

