recent_docs: 50

data_source: data
defaults:
  -
    scope:
      path: "data/tags/*.md"
    values:
      permalink: /:basename/
      layout: default
  -
    scope:
      path: "data/bibtex/*.md"
    values:
      permalink: /bib/:basename
      layout: bibtex
      
plugins:
  - jekyll-optional-front-matter
  
#collections_dir: data
#collections:
#  tags:
#    output: true
#    permalink: /:collection/:path/

