recent_docs: 50

data_source: data
defaults:
  -
    scope:
      path: "data/tags/*.md"
    values:
      permalink: /:basename/
      layout: default
  -
    scope:
      path: "data/bibtex/*.md"
    values:
      permalink: /:basename.bib/
      layout: bibtex   
  -
    scope:
      path: "data/json/*.md"
    values:
      permalink: /:basename.json/
      layout: json
  -
    scope:
      path: "all_bibtex.md"
    values:
      permalink: /all.bib
      layout: bibtex

  -
    scope:
      path: "all_json.md"
    values:
      permalink: /all.json/
      layout: json
      
plugins:
  - jekyll-optional-front-matter
  
#collections_dir: data
#collections:
#  tags:
#    output: true
#    permalink: /:collection/:path/

