recent_docs: 50

data_source: data
collections_dir: data

#collections:
#  tags:
#    output: true
#    permalink: /:collection/:path/

#permalink: /tagsaba/:basename/

defaults:
  -
    scope:
      type: "pages"
    values:
      permalink: /tagsaba/:basename/
